#ifndef	__ASM_CSKY_CSKY_H
#define	__ASM_CSKY_CSKY_H

#ifdef CONFIG_MMU
#define CK_RAM_BASE		CONFIG_RAM_BASE
#else
#define CK_RAM_BASE		CONFIG_RAM_BASE
#define CK_RAM_END		(CK_RAM_BASE + CONFIG_RAM_SIZE - DMA_UNCACHED_REGION)
#define CK_UNCACHED_RAM_BASE	CK_RAM_END
#endif /* CONFIG_MMU */

#endif	/* __ASM_CSKY_CSKY_H */
