# SPDX-License-Identifier: GPL-2.0
dtb-$(CONFIG_SOC_SOPHGO) += mango-sophgo-x8evb.dtb
dtb-$(CONFIG_SOC_SOPHGO) += mango-milkv-pioneer.dtb
dtb-$(CONFIG_SOC_SOPHGO) += mango-sophgo-pisces.dtb
dtb-$(CONFIG_SOC_SOPHGO) += mango-sophgo-x4evb.dtb
